### ISSUE TITLE
Cannot access confirmed balance

### ISSUE THREAD

**Issue by tiequan12345** [Nintondo/extension#5]
Running extension version 0.2.1, sent BEL to my nintondo address and it's been confirmed 1800+ blocks already, and the incoming transaction shows in the wallet, but I cannot send the funds or do anything with it.  It shows I have 0 balance available.  Do you have a fix for this?  Or at least a way for me to extract the private key for this derivation path so I can use this on a different wallet that works?

**Comment by kieled** [comment]
The derivation path is only related to the import via a 12-word mnemonic phrase. The actual problem that our indexer has solved is that your output contains inscriptions. And you can split your output into small parts that do not contain inscriptions for using your assets. But currently extension doesn't support this. 

So for the future we have some ideas about adding the ability to automatically handle this scenario in the extension

The derivation path is only related to importing using a 12-word mnemonic phrase. The real problem that our indexer has found is that your output contains inscriptions. And you can split your output into small parts that don't contain inscriptions to use your resources. But currently the extension does not support this. 

By the way, for the future we have some ideas about adding the possibility of automatic processing of this scenario to the extension

Derivation path you can find here: https://github.com/Nintondo/bellhdw/blob/main/ts_src/hd/private.ts#L24

Thanks for your feedback

**Comment by kieled** [comment]
The derivation path is only related to importing using a 12-word mnemonic phrase. The real problem that our indexer has found is that your output contains inscriptions. And you can split your output into small parts that don't contain inscriptions to use your resources. But currently the extension does not support this.

By the way, for the future we have some ideas about adding the possibility of automatic processing of this scenario to the extension

Derivation path you can find here: https://github.com/Nintondo/bellhdw/blob/main/ts_src/hd/private.ts#L24

Thanks for your feedback

**Comment by ocnu** [comment]
I am on 0.2.5.4 and seem to be experiencing the same issue. How do I resolve this? I am new to this.
