### ISSUE TITLE
Can't send out any inscriptions

### ISSUE THREAD

**Issue by GrahamBells** [Nintondo/extension#6]
Tested 0.2.1 and noticed that the Send button for inscriptions are gone. Went back to 0.2 and it's the same thing, cannot send out any inscriptions or bel-20 transfers.

**Comment by GrahamBells** [comment]
What's the derivation path used for Nintondo? Some people are trying to export the private key

**Comment by kieled** [comment]
Hi, we have already fixed this bug in our develop branch and will release a new version as soon as possible. tnx for your feedback. we will mention and close this PR when the release is published.

**Comment by GrahamBells** [comment]
Great to know, thanks!

**Comment by kieled** [comment]
Fixed! https://github.com/Nintondo/extension/releases/tag/0.2.2
