### ISSUE TITLE
Receiving Virus/Trojan Message Upon Downloading

### ISSUE THREAD

**Issue by jeffjagoe** [Nintondo/extension#7]
![image](https://github.com/Nintondo/extension/assets/47159832/b3339b40-f8cc-4347-9471-e4b79e70f7e9)

**Comment by kieled** [comment]
Thanks for your feedback. The version has been updated (only for chrome). Firefox update will be updated on version 0.2.3
https://github.com/Nintondo/extension/releases/tag/0.2.2
