### ISSUE TITLE
Failed Pushing Transaction

### ISSUE THREAD

**Issue by ocnu** [Nintondo/extension#98]
Getting a "Failed Pushing Transaction" when trying to send.

**Comment by kieled** [comment]
can you send screenshot of console output ?

To open console:

1. Go to "send" page
2. Click RMB 
3. Click "Inspect"
4. Try send bells again

**Comment by ocnu** [comment]
![image](https://github.com/user-attachments/assets/28fd30ff-4f9b-43ad-a14b-ea5da148c9c5)

I can't do it because now it's not loading

**Comment by kieled** [comment]
change address type to legacy

**Comment by ocnu** [comment]
How do I see the coins I sent to Native Segwit then?

**Comment by kieled** [comment]
native segwit will be activated after block 144000. then you will be allowed to see and spend your balance

**Comment by ocnu** [comment]
Thanks for the replies!

**Comment by ocnu** [comment]
My balance is loading now, but still getting "Failed Pushing Transaction" when trying to send. Any ideas?

**Comment by kieled** [comment]
which your address type ?

**Comment by ocnu** [comment]
Native segwit

**Comment by kieled** [comment]
You have reopened the problem before block 144k. Can you try again and check if your problem is relevant right now
